### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by toastyy00** [Widiskel/fintopio-mining-bot#2]
how to implement multi accounts on the bot that using session?

**Comment by copycatcodex** [comment]
create a new session. example.
- account 1
- account 2.

so if you run the bot. you ill run 2 accounts at the same time

**Comment by toastyy00** [comment]
what about the api_id & hash?  Does each account have to fill it in?

**Comment by Widiskel** [comment]
> what about the api_id & hash?  Does each account have to fill it in?

you just need 1 app id and hash for run multiple accounts, app id and hash its just way to connect with telegram api
