### ISSUE TITLE
Single Line Args

### ISSUE THREAD

**Issue by Gareryer** [Widiskel/fintopio-mining-bot#3]
--action=1 like below,
https://github.com/Freddywhest/RockyRabbitBot/blob/main/README.md

**Comment by Widiskel** [comment]
> --action=1 like below,
> https://github.com/Freddywhest/RockyRabbitBot/blob/main/README.md

unclesr isssue.

**Comment by Gareryer** [comment]
> > --action=1 like below,
> > https://github.com/Freddywhest/RockyRabbitBot/blob/main/README.md
> 
> unclesr isssue.
instead of wait to enter the next command can you make it like an argument when I can just pass it
https://github.com/Freddywhest/RockyRabbitBot/issues/1

**Comment by Widiskel** [comment]
> > > --action=1 like below,
> > > https://github.com/Freddywhest/RockyRabbitBot/blob/main/README.md
> > 
> > unclesr isssue.
> instead of wait to enter the next command can you make it like an argument when I can just pass it
> https://github.com/Freddywhest/RockyRabbitBot/issues/1

i don't know what do you mean ? 

u want to run with only 1 command ? run it on `screen` you can pass a `stuff`. so you dont need to manual input option like `3` after starting the bot
